require "nvchad.mappings"

-- add yours here

local map = vim.keymap.set
map("v", "p", "P", { noremap = true })
map("n", "cw", '"_cw', { noremap = true })
map("n", "cc", '"_cc', { noremap = true })
map("n", "C", '"_C', { noremap = true })
map("v", "c", '"_c', { noremap = true })
map("v", "ci{", '"_ci{', { noremap = true })
map("v", "ca{", '"_ca{', { noremap = true })
map("v", 'ci"', '"_ci"', { noremap = true })
map("v", 'ca"', '"_ca"', { noremap = true })
map("v", "ci[", '"_ci[', { noremap = true })
map("v", "ca[", '"_ca[', { noremap = true })
map("v", "ci(", '"_ci(', { noremap = true })
map("v", "ca(", '"_ca(', { noremap = true })
map("n", "dw", '"_dw', { noremap = true })
map("n", "dd", '"_dd', { noremap = true })
map("n", "D", '"_D', { noremap = true })
map("v", "d", '"_d', { noremap = true })
map("v", "di{", '"_di{', { noremap = true })
map("v", "da{", '"_da{', { noremap = true })
map("v", 'di"', '"_di"', { noremap = true })
map("v", 'da"', '"_da"', { noremap = true })
map("v", "di[", '"_di[', { noremap = true })
map("v", "da[", '"_da[', { noremap = true })
map("v", "di(", '"_di(', { noremap = true })
map("v", "da(", '"_da(', { noremap = true })
map("v", "r", '"_r', { noremap = true })
map("n", "r", '"_r', { noremap = true })
map("v", "R", '"_R', { noremap = true })
map("n", "R", '"_R', { noremap = true })
map("v", "s", "<cmd>write<cr>", { desc = "Save" })
map("v", "S", "<cmd>write<cr>", { desc = "Save" })
map("n", "s", "<cmd>write<cr>", { desc = "Save" })
map("n", "S", "<cmd>write<cr>", { desc = "Save" })

-- map({ "n", "i", "v" }, "<C-s>", "<cmd> w <cr>")
